"""schema inicial

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=300), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN', 'ATENDENTE', name='papel', native_enum=False, length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('wa_id', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('configuracao_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_minutos', sa.Integer(), nullable=False),
    sa.Column('antecedencia_minima_horas', sa.Integer(), nullable=False),
    sa.Column('janela_dias', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios_funcionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('abre', sa.Time(), nullable=False),
    sa.Column('fecha', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('bloqueios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['atendentes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloqueios_inicio'), 'bloqueios', ['inicio'], unique=False)
    op.create_table('conversas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.Enum('SITE', 'DIRETO', name='origem', native_enum=False, length=30), nullable=False),
    sa.Column('intencao', sa.String(length=30), nullable=True),
    sa.Column('estado_atual', sa.String(length=50), nullable=False),
    sa.Column('contexto', sa.JSON(), nullable=False),
    sa.Column('modo', sa.Enum('BOT', 'HUMANO', 'AGUARDANDO_EQUIPE', name='modo', native_enum=False, length=30), nullable=False),
    sa.Column('atendente_id', sa.Integer(), nullable=True),
    sa.Column('ultima_msg_cliente_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['atendente_id'], ['atendentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversas_cliente_id'), 'conversas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_conversas_modo'), 'conversas', ['modo'], unique=False)
    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendente_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('revogada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['atendente_id'], ['atendentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessoes_atendente_id'), 'sessoes', ['atendente_id'], unique=False)
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('placa', sa.String(length=8), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'placa', name='uq_veiculo_cliente_placa')
    )
    op.create_index(op.f('ix_veiculos_cliente_id'), 'veiculos', ['cliente_id'], unique=False)
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('servico_pretendido_id', sa.Integer(), nullable=True),
    sa.Column('servico_identificado_id', sa.Integer(), nullable=True),
    sa.Column('conversa_id', sa.Integer(), nullable=True),
    sa.Column('descricao_problema', sa.Text(), nullable=True),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servico_identificado_id'], ['servicos.id'], ),
    sa.ForeignKeyConstraint(['servico_pretendido_id'], ['servicos.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_cliente_id'), 'avaliacoes', ['cliente_id'], unique=False)
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('remetente', sa.Enum('CLIENTE', 'BOT', 'ATENDENTE', name='remetente', native_enum=False, length=30), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=120), nullable=True),
    sa.Column('midia_ref', sa.String(length=300), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id')
    )
    op.create_index(op.f('ix_mensagens_conversa_id'), 'mensagens', ['conversa_id'], unique=False)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'REAGENDADO', 'CANCELADO', 'CONCLUIDO', 'NAO_COMPARECEU', name='statusagendamento', native_enum=False, length=30), nullable=False),
    sa.Column('criado_por', sa.String(length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_avaliacao_id'), 'agendamentos', ['avaliacao_id'], unique=False)
    op.create_index(op.f('ix_agendamentos_data_hora_inicio'), 'agendamentos', ['data_hora_inicio'], unique=False)
    op.create_index('uq_agendamento_slot_ativo', 'agendamentos', ['data_hora_inicio'], unique=True, postgresql_where=sa.text("status IN ('PENDENTE','CONFIRMADO','REAGENDADO')"), sqlite_where=sa.text("status IN ('PENDENTE','CONFIRMADO','REAGENDADO')"))
    op.create_table('fotos_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('wa_media_id', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_media_id')
    )
    op.create_index(op.f('ix_fotos_avaliacao_avaliacao_id'), 'fotos_avaliacao', ['avaliacao_id'], unique=False)
    op.create_table('historico_agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.String(length=30), nullable=True),
    sa.Column('status_novo', sa.String(length=30), nullable=False),
    sa.Column('inicio_anterior', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inicio_novo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('autor', sa.String(length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_agendamento_agendamento_id'), 'historico_agendamento', ['agendamento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_agendamento_agendamento_id'), table_name='historico_agendamento')
    op.drop_table('historico_agendamento')
    op.drop_index(op.f('ix_fotos_avaliacao_avaliacao_id'), table_name='fotos_avaliacao')
    op.drop_table('fotos_avaliacao')
    op.drop_index('uq_agendamento_slot_ativo', table_name='agendamentos', postgresql_where=sa.text("status IN ('PENDENTE','CONFIRMADO','REAGENDADO')"), sqlite_where=sa.text("status IN ('PENDENTE','CONFIRMADO','REAGENDADO')"))
    op.drop_index(op.f('ix_agendamentos_data_hora_inicio'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_avaliacao_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_mensagens_conversa_id'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_avaliacoes_cliente_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    op.drop_index(op.f('ix_veiculos_cliente_id'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_sessoes_atendente_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index(op.f('ix_conversas_modo'), table_name='conversas')
    op.drop_index(op.f('ix_conversas_cliente_id'), table_name='conversas')
    op.drop_table('conversas')
    op.drop_index(op.f('ix_bloqueios_inicio'), table_name='bloqueios')
    op.drop_table('bloqueios')
    op.drop_table('servicos')
    op.drop_table('horarios_funcionamento')
    op.drop_table('configuracao_agenda')
    op.drop_table('clientes')
    op.drop_table('atendentes')
    # ### end Alembic commands ###
